# Generated by Tug's tagged-release workflow. Do not edit by hand.
class Tug < Formula
  desc "Deploy Serverpod applications to Coolify"
  homepage "https://github.com/mcquenji/tug"
  version "0.2.2"

  depends_on "fvm"
  depends_on "git"

  on_macos do
    depends_on macos: :sequoia
    on_arm do
      url "https://github.com/mcquenji/tug/releases/download/v0.2.2/tug-v0.2.2-macos-arm64.tar.gz"
      sha256 "4c243e3c14f576a09a1aed61e0ab057723b8311bae7a7b4ba3d82604c8c0b9bf"
    end
    on_intel do
      url "https://github.com/mcquenji/tug/releases/download/v0.2.2/tug-v0.2.2-macos-x64.tar.gz"
      sha256 "bca1a43ab39ae3bf27bd2bdd2765a771df8f9c6c9ce26e28dc7db058821da115"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mcquenji/tug/releases/download/v0.2.2/tug-v0.2.2-linux-arm64.tar.gz"
      sha256 "7dbdab9a041070d1a22af643009bb9406d81781a69ddffc03d6c81b21830caf8"
    end
    on_intel do
      url "https://github.com/mcquenji/tug/releases/download/v0.2.2/tug-v0.2.2-linux-x64.tar.gz"
      sha256 "84d289a4e6ebce8ae8a11f0389d48e1ce34789d65f40fc6b2757ac42d88dfe47"
    end
  end

  def install
    bin.install "tug"
  end

  test do
    assert_equal "tug #{version}", shell_output("#{bin}/tug --version").strip
  end
end
