# Generated by Tug's tagged-release workflow. Do not edit by hand.
class Tug < Formula
  desc "Deploy Serverpod applications to Coolify"
  homepage "https://github.com/mcquenji/tug"
  version "0.2.1"

  depends_on "fvm"
  depends_on "git"

  on_macos do
    depends_on macos: :sequoia
    on_arm do
      url "https://github.com/mcquenji/tug/releases/download/v0.2.1/tug-v0.2.1-macos-arm64.tar.gz"
      sha256 "570f408c00eaed7fbf4e5dae71772be0e933c96e11a1587cf4ba9a44f2050479"
    end
    on_intel do
      url "https://github.com/mcquenji/tug/releases/download/v0.2.1/tug-v0.2.1-macos-x64.tar.gz"
      sha256 "d051bdcebff3b8faccd5a09605c8a8e02f3b52c823c24bf10d2bb2b588b7a599"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mcquenji/tug/releases/download/v0.2.1/tug-v0.2.1-linux-arm64.tar.gz"
      sha256 "2a38f49b59a00737c227724b9f5c042b4fdca90b25eed99c52981c77714b9c5a"
    end
    on_intel do
      url "https://github.com/mcquenji/tug/releases/download/v0.2.1/tug-v0.2.1-linux-x64.tar.gz"
      sha256 "e06108443ddde4148388442f564a8631861840fcf2d1112372968f8c44b9e203"
    end
  end

  def install
    bin.install "tug"
  end

  test do
    assert_equal "tug #{version}", shell_output("#{bin}/tug --version").strip
  end
end
